-- ==========================================================================
-- Locations, factions, items, lore (hand-curated first pass from the notes)
-- ==========================================================================

insert into public.locations (id, campaign_id, name, kind, "desc", region, ruler, notes) values
  ('foi-l1',  'fist-of-ilmater', 'Triboar',            'Town',       'Seat of the Shields of the Crying God, liberated by the party in the Battle of Triboar. The guild hall holds floors of teleportation, dragons, and competence, each tended by an undead saint.', 'Sword Coast North', null, 'Weaver''s office sits above the guild floors. Teleportation circles cost money.'),
  ('foi-l2',  'fist-of-ilmater', 'Phandalin',          'Town',       'Frontier town of townmaster Harbin Wester, Sister Garaele, and the Shrine of Luck. Booming again now the mine has reopened.', 'Sword Coast North', 'Harbin Wester', 'The party''s rescued Gragmaw goblins serve as its militia under Targor Bloodsword.'),
  ('foi-l3',  'fist-of-ilmater', 'Longsaddle',         'Town',       'Home of the Harpell wizard family and, formerly, Trade Off''s headquarters and slaughterhouse. An illusion dome upheld by the Harpells covers it.', 'Sword Coast North', 'The Harpells', 'Ostever''s Slaughterhouse hid Trade Off''s dungeon. Penelope Harpell blew the HQ sky-high.'),
  ('foi-l4',  'fist-of-ilmater', 'Wave Echo Cave',     'Mine',       'Lost mine of the Phandelver''s Pact, home of the Forge of Spells and its beholder Guardian. A new Pact with the dwarves restarted the mine, with the guild taking a percentage.', 'near Phandalin', null, 'Where Iarno fell, and where the clown revealed himself as Mephistopheles.'),
  ('foi-l5',  'fist-of-ilmater', 'Gragmaw Castle',     'Castle',     'Ruined castle held by King Grol''s goblins, where Gundren Rockseeker was held and interrogated by the drow priestess Vyerith.', 'Sword Coast North', null, 'Its north-east tower was sealed by a magical sun-and-moon lock.'),
  ('foi-l6',  'fist-of-ilmater', 'Barovia',            'Domain of Dread', 'Strahd von Zarovich''s misty prison-realm, entered by the party in session 77 and escaped in session 146. The Vistani alone walk its mists freely.', 'The Mists', 'Strahd von Zarovich (dec.)', 'The mists smell of rotten glass. Leaving without a talisman means days of suffocation.'),
  ('foi-l7',  'fist-of-ilmater', 'Vallaki',            'Town',       'Palisaded town of forced weekly festivals under Baron Vargas Vallakovich. The party unmasked Lady Wachter as a succubus here — before werewolves destroyed the town entirely.', 'Barovia', null, 'Its children were carried to the wolf den; the party brought the survivors to Krezk.'),
  ('foi-l8',  'fist-of-ilmater', 'Castle Ravenloft',   'Castle',     'Strahd''s castle, seized late in the saga by Baba Lysaga and her fiendish backers. Crawled from catacombs to throne room, where both witch and vampire finally fell.', 'Barovia', null, 'A pulsing crystal heart powered its defences until the party destroyed it.'),
  ('foi-l9',  'fist-of-ilmater', 'The Amber Temple',   'Temple',     'A cold, dark temple where ancient wizards sealed arch evils in amber sarcophagi — rumored to be where Strahd became a vampire. Kept by the amnesiac lich Exethanter.', 'Barovia', null, 'Barendd refused the Corpse Star''s bargain here. Rahadin''s stabbed body was found at its door.'),
  ('foi-l10', 'fist-of-ilmater', 'Krezk',              'Village',    'Walled settlement of mayor Dmitry Kreskov, near the blessed pool of St. Markovia and the Abbey where the mad Abbot built a bride for Strahd.', 'Barovia', 'Dmitry Kreskov', 'Vallaki''s rescued children were brought here.'),
  ('foi-l11', 'fist-of-ilmater', 'Neverwinter',        'City',       'City of Lord Protector Dagult Neverember. The party stayed at The Moonstone Mask and researched the Shadowfell at the House of Knowledge.', 'Sword Coast North', 'Dagult Neverember', 'Teleportation-circle users owe the city a day of monster-hunting.'),
  ('foi-l12', 'fist-of-ilmater', 'Grudd Haug',         'Giant Den',  'Chief Guh''s den, built to dam a river — a hub where hill giants and goblinoids kidnapped people to eat or sell. Cleared by the party.', 'Sword Coast North', 'Chief Guh (dec.)', 'The survivor Hruk revealed Theldin was sold to fire giants of a cult headed for the Shadow of Mount Hotenow.'),
  ('foi-l13', 'fist-of-ilmater', 'Mount Hotenow',      'Volcano',    'The volcano whose eruption caused the Ruining fifty years ago. It has an echo of itself inside the Shadowfell, with the Starforge amid an acid lake near its top.', 'near Neverwinter', null, 'Reached through a one-way dungeon of seven iron doors, past the dragon Calumnus.'),
  ('foi-l14', 'fist-of-ilmater', 'Port Llast',         'Port Town',  'Fallen to corrupted, red-eyed frost giants and two dragons who arrived aboard the giant ship Krigvind. The fog-shrouded town is filled with corpses.', 'north of Neverwinter', null, null);

insert into public.factions (id, campaign_id, name, sigil, "desc", allegiance) values
  ('foi-f1', 'fist-of-ilmater', 'Shields of the Crying God', 'S',  'The party''s heroes guild in Triboar, led by Weaver — the last surviving hero guild; the rest were wiped out by the SpellPlague. Its ranks include the Elite Four and undead saints.', 'Ally'),
  ('foi-f2', 'fist-of-ilmater', 'The Vistani',               'V',  'People of stories who alone can walk the mists between Domains of Dread. They keep the dusk elves close and would not betray Strahd — but Madam Eva''s talisman led the party home.', 'Neutral'),
  ('foi-f3', 'fist-of-ilmater', 'Keepers of the Feather',    'K',  'The were-raven Martikov family — Urwin at the Blue Water Inn, Davian at the Wizard of Wines — who long protected Vallaki and pledged their wings against Strahd.', 'Ally'),
  ('foi-f4', 'fist-of-ilmater', 'Zhentarim',                 'Z',  'The Black Network: mercenaries, spies and assassins who hunted the Gauntlets of Vonindod alongside Mephistopheles'' fiends. Their soldiers killed Karn at Nesmé.', 'Hostile'),
  ('foi-f5', 'fist-of-ilmater', 'The Black Spider',          'B',  'Drow-fronted operation that sought the Forge of Spells through agents like Vyerith and Nazznar — ultimately revealed as a disguise of the archdevil Mephistopheles.', 'Hostile'),
  ('foi-f6', 'fist-of-ilmater', 'The Harpers',               'H',  'Elven investigators who police the North. Ariana Riverlost''s trio took Orcsplitter into safekeeping for Weaver in exchange for promised magic items.', 'Ally'),
  ('foi-f7', 'fist-of-ilmater', 'Cult of Gomoth',            'G',  'A cult of fire beings formed by the mad fire giant Gomoth to awaken the primordial Maegera the Inferno. Its giants bought Theldin and marched for the Shadow of Mount Hotenow.', 'Hostile'),
  ('foi-f8', 'fist-of-ilmater', 'Trade Off',                 'T',  'Smuggling company out of Longsaddle led by Kriv, which Tillem unknowingly served as a delivery boy. It kidnapped Wom, and was destroyed by the party and Penelope Harpell.', 'Hostile');

insert into public.items (id, campaign_id, name, kind, "desc") values
  ('foi-i1', 'fist-of-ilmater', 'The Sunsword',             'Weapon',     'Sergey''s blade — ''only sun can kill me'', wrote Strahd. Found inside a scarecrow at the Abbey; Barendd drove it through Strahd''s heart in his coffin.'),
  ('foi-i2', 'fist-of-ilmater', 'Tome of Strahd',           'Book',       'Strahd''s ancient tome, found above the Abbot''s hearth, revealing his weaknesses. Cursed to make its reader its protector — a curse Oliver could not break.'),
  ('foi-i3', 'fist-of-ilmater', 'Symbol of Ravenkind',      'Holy Relic', 'A powerful force of good and protection from Madam Eva''s reading, found in an adamantine tower-room of Castle Ravenloft.'),
  ('foi-i4', 'fist-of-ilmater', 'Orcsplitter',              'War Axe',    'King Torhild Flametongue''s legendary axe. It filled Mort and Fynn with unrest as unworthy wielders but accepted Barendd; now with the Harpers for safekeeping.'),
  ('foi-i5', 'fist-of-ilmater', 'Karn''s Ruby',             'Gem',        'Taken from Karn''s shattered body after his last stand at Nesmé. When Fynn held it, it felt warm and filled with love.'),
  ('foi-i6', 'fist-of-ilmater', 'The Mist Talisman',        'Talisman',   'Prepared by Madam Eva and keyed to the party''s home world. Cold to the touch, it tugged Fynn along the right path through the mists.');

insert into public.lore (id, campaign_id, title, text) values
  ('foi-lo1', 'fist-of-ilmater', 'The Shields of the Crying God', 'The last surviving heroes guild — every other was wiped out by the SpellPlague. Ilmater, the Crying God, weeps for those who suffer; his shields carry the suffering instead. Karn died as one.'),
  ('foi-lo2', 'fist-of-ilmater', 'The Mists and the Domains of Dread', 'The mists ferry the unwilling between Domains of Dread and smell of rotten glass. Only the Vistani walk them freely; a mist talisman keyed to a world can lead you home — if you don''t suffocate first.'),
  ('foi-lo3', 'fist-of-ilmater', 'The Balance of the Hells', 'Mephistopheles has made demons and devils fight together, breaking the balance. He gathers power in every world — obsidian obelisks pulled through portals, dread domains seeded, dragons stolen — for a next step no one has named.');
